name: C++ CI

on:
  push:
    branches: [ "main", "lib" ]
  pull_request:
    branches: [ "main", "lib" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Check format
        run: bash -c 'shopt -s globstar; clang-format --dry-run -Werror src/**/*.cpp src/**/*.h'
        working-directory: ${{ github.workspace }}

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgl1-mesa-dev libx11-dev zlib1g-dev
          sudo apt-get install -y libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev

      - name: Build with make
        run: make -j4 debug
        working-directory: ${{ github.workspace }}

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with make
        run: make -j4 debug
        working-directory: ${{ github.workspace }}
